// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/v1/emailverifier.proto

package emailverifierv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VerifyRequest is the input to the Verify RPC / HTTP handler.
type VerifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Email string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Options control which optional checks are activated.
	Options       *VerifyOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_proto_v1_emailverifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_emailverifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_emailverifier_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyRequest) GetOptions() *VerifyOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type VerifyOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enable_domain_suggest activates typo detection on the domain portion.
	// Off by default; see D-8.
	EnableDomainSuggest bool `protobuf:"varint,1,opt,name=enable_domain_suggest,json=enableDomainSuggest,proto3" json:"enable_domain_suggest,omitempty"`
	// extra_disposable_domains appends caller-supplied domains to the
	// built-in disposable list. See D-5.
	ExtraDisposableDomains []string `protobuf:"bytes,2,rep,name=extra_disposable_domains,json=extraDisposableDomains,proto3" json:"extra_disposable_domains,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VerifyOptions) Reset() {
	*x = VerifyOptions{}
	mi := &file_proto_v1_emailverifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOptions) ProtoMessage() {}

func (x *VerifyOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_emailverifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOptions.ProtoReflect.Descriptor instead.
func (*VerifyOptions) Descriptor() ([]byte, []int) {
	return file_proto_v1_emailverifier_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyOptions) GetEnableDomainSuggest() bool {
	if x != nil {
		return x.EnableDomainSuggest
	}
	return false
}

func (x *VerifyOptions) GetExtraDisposableDomains() []string {
	if x != nil {
		return x.ExtraDisposableDomains
	}
	return nil
}

// VerifyResponse is the unified result of all enabled checks.
type VerifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The original email address that was verified.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Syntax contains the parsed components of the address.
	Syntax *Syntax `protobuf:"bytes,2,opt,name=syntax,proto3" json:"syntax,omitempty"`
	// mx contains DNS MX record information for the domain.
	Mx *MXResult `protobuf:"bytes,3,opt,name=mx,proto3" json:"mx,omitempty"`
	// disposable is true when the domain belongs to a known DEA provider.
	Disposable bool `protobuf:"varint,4,opt,name=disposable,proto3" json:"disposable,omitempty"`
	// role_account is true when the username is a well-known role address.
	RoleAccount bool `protobuf:"varint,5,opt,name=role_account,json=roleAccount,proto3" json:"role_account,omitempty"`
	// free is true when the domain is a known free email provider.
	Free bool `protobuf:"varint,6,opt,name=free,proto3" json:"free,omitempty"`
	// suggestion is a typo-corrected domain, populated only when
	// VerifyOptions.enable_domain_suggest is true and a likely typo is found.
	// Empty string means no suggestion.
	Suggestion    string `protobuf:"bytes,7,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_proto_v1_emailverifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_emailverifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_emailverifier_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyResponse) GetSyntax() *Syntax {
	if x != nil {
		return x.Syntax
	}
	return nil
}

func (x *VerifyResponse) GetMx() *MXResult {
	if x != nil {
		return x.Mx
	}
	return nil
}

func (x *VerifyResponse) GetDisposable() bool {
	if x != nil {
		return x.Disposable
	}
	return false
}

func (x *VerifyResponse) GetRoleAccount() bool {
	if x != nil {
		return x.RoleAccount
	}
	return false
}

func (x *VerifyResponse) GetFree() bool {
	if x != nil {
		return x.Free
	}
	return false
}

func (x *VerifyResponse) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

// Syntax holds the parsed components and validity of an email address.
type Syntax struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // local part before the @
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`     // domain part after the @
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`      // true if the address passes format validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Syntax) Reset() {
	*x = Syntax{}
	mi := &file_proto_v1_emailverifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Syntax) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Syntax) ProtoMessage() {}

func (x *Syntax) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_emailverifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Syntax.ProtoReflect.Descriptor instead.
func (*Syntax) Descriptor() ([]byte, []int) {
	return file_proto_v1_emailverifier_proto_rawDescGZIP(), []int{3}
}

func (x *Syntax) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Syntax) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Syntax) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// MXResult holds the DNS MX lookup outcome for a domain.
type MXResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasMxRecord   bool                   `protobuf:"varint,1,opt,name=has_mx_record,json=hasMxRecord,proto3" json:"has_mx_record,omitempty"`
	Records       []*MXRecord            `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MXResult) Reset() {
	*x = MXResult{}
	mi := &file_proto_v1_emailverifier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MXResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MXResult) ProtoMessage() {}

func (x *MXResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_emailverifier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MXResult.ProtoReflect.Descriptor instead.
func (*MXResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_emailverifier_proto_rawDescGZIP(), []int{4}
}

func (x *MXResult) GetHasMxRecord() bool {
	if x != nil {
		return x.HasMxRecord
	}
	return false
}

func (x *MXResult) GetRecords() []*MXRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// MXRecord represents a single DNS MX entry.
type MXRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`  // fully-qualified mail host name
	Pref          uint32                 `protobuf:"varint,2,opt,name=pref,proto3" json:"pref,omitempty"` // preference (lower = higher priority)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MXRecord) Reset() {
	*x = MXRecord{}
	mi := &file_proto_v1_emailverifier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MXRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MXRecord) ProtoMessage() {}

func (x *MXRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_emailverifier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MXRecord.ProtoReflect.Descriptor instead.
func (*MXRecord) Descriptor() ([]byte, []int) {
	return file_proto_v1_emailverifier_proto_rawDescGZIP(), []int{5}
}

func (x *MXRecord) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MXRecord) GetPref() uint32 {
	if x != nil {
		return x.Pref
	}
	return 0
}

// LookupError represents a structured error from a DNS lookup failure.
type LookupError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupError) Reset() {
	*x = LookupError{}
	mi := &file_proto_v1_emailverifier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupError) ProtoMessage() {}

func (x *LookupError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_emailverifier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupError.ProtoReflect.Descriptor instead.
func (*LookupError) Descriptor() ([]byte, []int) {
	return file_proto_v1_emailverifier_proto_rawDescGZIP(), []int{6}
}

func (x *LookupError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LookupError) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_proto_v1_emailverifier_proto protoreflect.FileDescriptor

const file_proto_v1_emailverifier_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/v1/emailverifier.proto\x12\x10emailverifier.v1\"`\n" +
	"\rVerifyRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x129\n" +
	"\aoptions\x18\x02 \x01(\v2\x1f.emailverifier.v1.VerifyOptionsR\aoptions\"}\n" +
	"\rVerifyOptions\x122\n" +
	"\x15enable_domain_suggest\x18\x01 \x01(\bR\x13enableDomainSuggest\x128\n" +
	"\x18extra_disposable_domains\x18\x02 \x03(\tR\x16extraDisposableDomains\"\xfb\x01\n" +
	"\x0eVerifyResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x120\n" +
	"\x06syntax\x18\x02 \x01(\v2\x18.emailverifier.v1.SyntaxR\x06syntax\x12*\n" +
	"\x02mx\x18\x03 \x01(\v2\x1a.emailverifier.v1.MXResultR\x02mx\x12\x1e\n" +
	"\n" +
	"disposable\x18\x04 \x01(\bR\n" +
	"disposable\x12!\n" +
	"\frole_account\x18\x05 \x01(\bR\vroleAccount\x12\x12\n" +
	"\x04free\x18\x06 \x01(\bR\x04free\x12\x1e\n" +
	"\n" +
	"suggestion\x18\a \x01(\tR\n" +
	"suggestion\"R\n" +
	"\x06Syntax\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\"d\n" +
	"\bMXResult\x12\"\n" +
	"\rhas_mx_record\x18\x01 \x01(\bR\vhasMxRecord\x124\n" +
	"\arecords\x18\x02 \x03(\v2\x1a.emailverifier.v1.MXRecordR\arecords\"2\n" +
	"\bMXRecord\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04pref\x18\x02 \x01(\rR\x04pref\"A\n" +
	"\vLookupError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetailsB>Z<github.com/shepard-labs/go-mailsafe/proto/v1;emailverifierv1b\x06proto3"

var (
	file_proto_v1_emailverifier_proto_rawDescOnce sync.Once
	file_proto_v1_emailverifier_proto_rawDescData []byte
)

func file_proto_v1_emailverifier_proto_rawDescGZIP() []byte {
	file_proto_v1_emailverifier_proto_rawDescOnce.Do(func() {
		file_proto_v1_emailverifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_emailverifier_proto_rawDesc), len(file_proto_v1_emailverifier_proto_rawDesc)))
	})
	return file_proto_v1_emailverifier_proto_rawDescData
}

var file_proto_v1_emailverifier_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_v1_emailverifier_proto_goTypes = []any{
	(*VerifyRequest)(nil),  // 0: emailverifier.v1.VerifyRequest
	(*VerifyOptions)(nil),  // 1: emailverifier.v1.VerifyOptions
	(*VerifyResponse)(nil), // 2: emailverifier.v1.VerifyResponse
	(*Syntax)(nil),         // 3: emailverifier.v1.Syntax
	(*MXResult)(nil),       // 4: emailverifier.v1.MXResult
	(*MXRecord)(nil),       // 5: emailverifier.v1.MXRecord
	(*LookupError)(nil),    // 6: emailverifier.v1.LookupError
}
var file_proto_v1_emailverifier_proto_depIdxs = []int32{
	1, // 0: emailverifier.v1.VerifyRequest.options:type_name -> emailverifier.v1.VerifyOptions
	3, // 1: emailverifier.v1.VerifyResponse.syntax:type_name -> emailverifier.v1.Syntax
	4, // 2: emailverifier.v1.VerifyResponse.mx:type_name -> emailverifier.v1.MXResult
	5, // 3: emailverifier.v1.MXResult.records:type_name -> emailverifier.v1.MXRecord
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_emailverifier_proto_init() }
func file_proto_v1_emailverifier_proto_init() {
	if File_proto_v1_emailverifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_emailverifier_proto_rawDesc), len(file_proto_v1_emailverifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_emailverifier_proto_goTypes,
		DependencyIndexes: file_proto_v1_emailverifier_proto_depIdxs,
		MessageInfos:      file_proto_v1_emailverifier_proto_msgTypes,
	}.Build()
	File_proto_v1_emailverifier_proto = out.File
	file_proto_v1_emailverifier_proto_goTypes = nil
	file_proto_v1_emailverifier_proto_depIdxs = nil
}
